### ISSUE TITLE
Error, Cannot call method 'get_shader_parameter' on a null value, Godot version 4.1.1.

### ISSUE THREAD

**Issue by SteelHorseGames** [CBerry22/Buoyancy-in-Godot-4#2]
I get this error with this code, which is identical to the one shown in the video, the only exception being names and things but that's it all the same base things are the same.

the code: 
extends MeshInstance3D

var material: ShaderMaterial
var noise: Image

var noise_scale: float
var time_scale: float
var height_scale: float

var time: float

# Called when the node enters the scene tree for the first time.
func _ready():
	material = mesh.surface_get_material(0)
	noise = material.get_shader_parameter("wave").noise.get_seamless_image(512, 512)
	noise_scale = material.get_shader_parameter("noise_scale")
	time_scale = material.get_shader_parameter("time_scale")
	height_scale = material.get_shader_parameter("height_scale")

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	time += delta
	material.set_shader_parameter("wave_time", time)

func get_height(world_position: Vector3) -> float:
	var uv_x = wrapf(world_position.x / noise_scale + time * time_scale, 0, 1)
	var uv_y = wrapf(world_position.z / noise_scale + time * time_scale, 0, 1)

	var pixel_pos = Vector2(uv_x * noise.get_width(), uv_y * noise.get_height())
	return global_position.y + noise.get_pixelv(pixel_pos).r * height_scale;

If you have any idea what's wrong please tell me I cannot finish my water system until I squash this bug.

**Comment by CBerry22** [comment]
The error message suggests your material variable is null. Have you tried placing a breakpoint and ensuring material isn't null?

**Comment by SteelHorseGames** [comment]
How can I check that my material isn't null, I'm very new to Godot and gdscript. I know how to place a breakpoint in the script though, but I think I know what you mean ill try it.

**Comment by SteelHorseGames** [comment]
here i have to images they have different points I placed breakpoints at
![BreakPointAtDeclarationOfMaterial](https://github.com/CBerry22/Buoyancy-in-Godot-4/assets/146688971/db1a7af4-6f39-4953-a1f4-85b30c60b3e5)
![BreakpointAtShaderMaterial](https://github.com/CBerry22/Buoyancy-in-Godot-4/assets/146688971/7e13ba40-2107-4bdb-8311-f997d1ca8800)

**Comment by SteelHorseGames** [comment]
I watched a debugging video and yes "material" is "<null>" as seen now I can fix that thx for the help in identifying the problem, I  don't know why it's null though it shouldn't be, thanks.

**Comment by SteelHorseGames** [comment]
Alright i finally figured it out and it all works now, really thankful if you hadn't told me that I probably wouldn't have ever figured it out and would have been discouraged a lot from being really frustrated, really thx.
